[project]
name = "newsletter-spike-mailchimp"
version = "0.0.1"
dependencies = [
    "Django>=4.2,<5",
    "mailchimp-marketing",
    "mjml-python",
    "queryish",
    "wagtail",
]

[tool.ruff]
line-length = 88
