# Generated by Django 4.2.11 on 2024-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='newsletter_audience',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='newsletter_audience_segment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
