# Generated by Django 4.2.11 on 2024-04-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_standardpage_newsletter_audience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('audience_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('segment_id', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='newsletter_audience',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='newsletter_audience_segment',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='newsletter_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.newsletteraudience'),
        ),
    ]
